### ISSUE TITLE
Maybe you don't know

### ISSUE THREAD

**Issue by jaclas** [luizvaz/DelphiEncryptionCompendium#1]
https://github.com/winkelsdorf/DelphiEncryptionCompendium

**Comment by luizvaz** [comment]
What you mean? I rewrote this DEC from DEC 3.0 just to have compatible results.
DEC 5.0 and above don't produce the same results from DEC 3.0 due to changes on initialization values.

**Comment by jaclas** [comment]
Okay, I haven't read the details, so good luck and I'm sorry for the confusion.
